#PLEASE RUN THE PROGRAM
import api
print("Enter all the inputs as numbers")
A=input("Please enter your age <type-int64>:")
print("------------------------------------------------------")
B=input("Gender,Enter: \n 0-Female \n 1-Male :")
print("------------------------------------------------------")
C=input("Chest pain type,Enter: \n 0-None \n 1- Typical angina \n 2-Atypical angina \n 3-Non-Anginal \n 4-Asymptomatic :")
print("------------------------------------------------------")
D=input("Resting blood pressure <type-int64>:")
print("------------------------------------------------------")
E=input("Serum cholestrol in mg/dl <type-int64>:")
print("------------------------------------------------------")
F=input("Fasting blood sugar > 120mg/dl,Enter: \n 0-False \n 1-True:")
print("------------------------------------------------------")
G=input("Resting Electrocardiograph results,Enter: \n 0-Normal \n 1-Having ST-T wave abnormality \n 2-Showing probable or definite left ventricular hypertrophy :")
print("------------------------------------------------------")
H=input("Maximum heart-rate acheived <type-int64>:")
print("------------------------------------------------------")
I=input("Exercise induced angina,Enter: \n 0-No \n 1-Yes :")
print("------------------------------------------------------")
J=input("ST depression induced by exercise relative to rest <type-int64>:")
print("------------------------------------------------------")
K=input("The slope of the peak exercise ST segment,Enter: \n 1-Upsloping \n 2-Flat \n 3-Downsloping :")
print("------------------------------------------------------")
L=input("Number of major vessels(0-3) coloured by flouroscopy :")
print("------------------------------------------------------")
M=input("Thalium stress test result,Enter: \n 0-Normal \n 1-Fixed defect \n 2-Reversable defect :")
print("------------------------------------------------------")
api.predict(A,B,C,D,E,F,G,H,I,J,K,L,M)
